apiVersion: v1 
kind: Service
metadata:
  name: postgres-service
  namespace: tristan
spec:
  selector:
    app: twoge-postgres
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432