apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: tristan
spec:
  storageClassName: db-storage
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce