apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: tristan
spec:
  selector:
    matchLabels: # This is the label that the deployment will use to select the pods it manages
      app: twoge
  replicas: 2
  template: # This is the pod template that the deployment will use to create new pods
    metadata:
      labels:
        app: twoge # This is the label that the pod will use to identify itself
    spec:
      containers:
        - name: twoge-container
          image: zimmermantr/twoge_kube:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: database-name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: twoge-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twoge-secret
                  key: postgres-password
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: database-port
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: database-host
            - name: DATABASE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: database-type
            - name: SQLALCHEMY_DATABASE_URI 
              value: "$(DATABASE_TYPE)://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DATABASE_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3