apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: tristan
spec:
  replicas: 1
  selector:
    matchLabels: # This is the label that the deployment will use to select the pods it manages
      app: twoge-postgres
  template: # This is the pod template that the deployment will use to create new pods
    metadata:
      labels:
        app: twoge-postgres # This is the label that the pod will use to identify itself
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          volumeMounts:
            - name: tristan-storage
              mountPath: /var/lib/postgresql
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          ports: 
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: twoge-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twoge-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: database-name
            - name: PGDATA  # This will tell PostgreSQL to use the subdirectory
              value: /var/lib/postgresql/pgdata
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
      volumes: 
        - name: tristan-storage
          persistentVolumeClaim:
            claimName: db-pvc