apiVersion: v1 
kind: Service
metadata:
  name: postgres-service
  namespace: tristan
spec:
  selector: # This is the label that the service will use to select the pods it will route traffic to
    app: twoge-postgres
  type: ClusterIP # This will expose the service on an internal IP in the cluster
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432