apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: tristan
spec:
  storageClassName: tristan-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce