services:
  database:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - assessment4
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: zimmermantr/twoge_kube
    container_name: backend
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - assessment4

networks:
  assessment4:
    name: assessment4
    driver: bridge

volumes:
  postgres-data: {}